### ISSUE TITLE
[UX] Box stays purple when unticked

### ISSUE THREAD

**Issue by FrenchSean** [goodytwohews/ts-tree-bugger#5]
Hey,

Awesome extension! Really. Just thought I'd share a small UX issue:

 When you untick a *card_section*, in the settings of the extension, it stays purple. It makes it hard to see what you ticked/unticked.

[![alt](http://take.ms/AaNGx4)](http://take.ms/AaNGx4)

It would be best if the unticked box can stay white, instead of purple, to just see at a glance which section is enabled/disabled.

Cheers :-)

Sean

**Comment by Brydom** [comment]
Heyo Sean!

Thanks for the note, I've gone and made it so that the unchecked boxes are white so they're clearly defined now :)

![https://screenshot.click/be-super-nice-b66jd.png](https://screenshot.click/be-super-nice-b66jd.png)
